#!/bin/sh -e

export DESTDIR="$1"
# Build fails with gcc 12 due to -Werror.
export CFLAGS="$CFLAGS -Wno-error"

patch -p1 < no-evdev.patch

meson \
    --prefix=/usr \
    -Ddefault-wallpaper=false \
    -Dzsh-completions=false \
    -Dbash-completions=false \
    -Dfish-completions=false \
    -Dxwayland=disabled \
    . build

ninja -C build
ninja -C build install
