#!/bin/sh -e

# build libevdev
# Needed until https://codeberg.org/kiss-community/repo/commit/22a38a3d6950c1ec134feec299703f9aa5138b97 is merged

zig build \
    --prefix /usr \
    --search-prefix /usr \
    -Drelease-safe \
    -Dtarget=x86_64-linux-gnu
