#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
	-D GLFW_BUILD_WAYLAND=1 \
  -D GLFW_BUILD_X11=0 \
	-D BUILD_SHARED_LIBS=1 \
	-D CMAKE_INSTALL_LIBDIR=lib \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D CMAKE_BUILD_TYPE=Release

cmake --build build

DESTDIR="$1" cmake --install build
