#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dtests=false \
    -Dintrospection=disabled \
    -Dman=false \
    -Dgtk_doc=false \
    -Ddocbook_docs=disabled \
    . build

ninja -C build
ninja -C build install
