#!/bin/sh -e

for p in *.patch; do
	patch -p1 < "$p"
done

# Disable debugging and development "stuff".
: > mk/devel.mk

CFLAGS="$CFLAGS -fcommon"

make -j1 \
    PYTHON=python \
    bios efi64 installer

make -j1 \
    INSTALLROOT="$1" \
    MANDIR=/usr/share/man \
    SBINDIR=/usr/bin \
    AUXDIR=/usr/lib/syslinux \
    bios efi64 install
