#!/bin/sh -e

./configure \
	--prefix=/usr \
	--libexecdir=/usr/bin \
	--localstatedir=/var \
	--disable-systemd-service \
	--disable-manual-pages

make
make DESTDIR="$1" install

# Install main.conf
mkdir -p "$1/etc/iwd"
cp -f main.conf "$1/etc/iwd/main.conf"

# Install runit service.
mkdir -p "$1/etc/sv/iwd"
cp -f iwd.run "$1/etc/sv/iwd/run"
ln -sf /run/runit/supervise.iwd "$1/etc/sv/iwd/supervise"
