#!/bin/sh -e

export DESTDIR="$1"

for p in *.patch; do
    patch -p1 < "$p"
done

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dtests=disabled \
    -Dsession-managers="['media-session']" \
    -Dudev=enabled \
    -Dudevrulesdir=/usr/lib/udev/rules.d \
    . build

ninja -C build
ninja -C build install

:>"$1/usr/share/pipewire/media-session.d/with-alsa"
